# From https://github.com/adafruit/Adafruit-Thermal-Printer-Library

# CHARSET_USA = 0           # American character set
# CHARSET_FRANCE = 1        # French character set
# CHARSET_GERMANY = 2       # German character set
# CHARSET_UK = 3            # UK character set
# CHARSET_DENMARK1 = 4      # Danish character set 1
# CHARSET_SWEDEN = 5        # Swedish character set
# CHARSET_ITALY = 6         # Italian character set
# CHARSET_SPAIN1 = 7        # Spanish character set 1
# CHARSET_JAPAN = 8         # Japanese character set
# CHARSET_NORWAY = 9        # Norwegian character set
# CHARSET_DENMARK2 = 10     # Danish character set 2
# CHARSET_SPAIN2 = 11       # Spanish character set 2
# CHARSET_LATINAMERICA = 12 # Latin American character set
# CHARSET_KOREA = 13        # Korean character set
# CHARSET_SLOVENIA = 14     # Slovenian character set
# CHARSET_CROATIA = 14      # Croatian character set
# CHARSET_CHINA = 15        # Chinese character set
# CODEPAGE_CP437 = 0    # USA, Standard Europe character code table
# CODEPAGE_KATAKANA = 1 # Katakana (Japanese) character code table
# CODEPAGE_CP850 = 2    # Multilingual character code table
# CODEPAGE_CP860 = 3    # Portuguese character code table
# CODEPAGE_CP863 = 4    # Canadian-French character code table
# CODEPAGE_CP865 = 5    # Nordic character code table
# CODEPAGE_WCP1251 = 6  # Cyrillic character code table
# CODEPAGE_CP866 = 7    # Cyrillic #2 character code table
# CODEPAGE_MIK = 8      # Cyrillic/Bulgarian character code table
# CODEPAGE_CP755 = 9    # East Europe, Latvian 2 character code table
# CODEPAGE_IRAN = 10    # Iran 1 character code table
# CODEPAGE_CP862 = 15   # Hebrew character code table
# CODEPAGE_WCP1252 = 16 # Latin 1 character code table
# CODEPAGE_WCP1253 = 17 # Greek character code table
# CODEPAGE_CP852 = 18   # Latin 2 character code table
# CODEPAGE_CP858 = 19 # Multilingual Latin 1 + Euro character code table
# CODEPAGE_IRAN2 = 20 # Iran 2 character code table
# CODEPAGE_LATVIAN = 21     # Latvian character code table
# CODEPAGE_CP864 = 22       # Arabic character code table
# CODEPAGE_ISO_8859_1 = 23  # West Europe character code table
# CODEPAGE_CP737 = 24       # Greek character code table
# CODEPAGE_WCP1257 = 25     # Baltic character code table
# CODEPAGE_THAI = 26        # Thai character code table
# CODEPAGE_CP720 = 27       # Arabic character code table
# CODEPAGE_CP855 = 28       # Cyrillic character code table
# CODEPAGE_CP857 = 29       # Turkish character code table
# CODEPAGE_WCP1250 = 30     # Central Europe character code table
# CODEPAGE_CP775 = 31       # Baltic character code table
# CODEPAGE_WCP1254 = 32     # Turkish character code table
# CODEPAGE_WCP1255 = 33     # Hebrew character code table
# CODEPAGE_WCP1256 = 34     # Arabic character code table
# CODEPAGE_WCP1258 = 35     # Vietnam character code table
# CODEPAGE_ISO_8859_2 = 36  # Latin 2 character code table
# CODEPAGE_ISO_8859_3 = 37  # Latin 3 character code table
# CODEPAGE_ISO_8859_4 = 38  # Baltic character code table
# CODEPAGE_ISO_8859_5 = 39  # Cyrillic character code table
# CODEPAGE_ISO_8859_6 = 40  # Arabic character code table
# CODEPAGE_ISO_8859_7 = 41  # Greek character code table
# CODEPAGE_ISO_8859_8 = 42  # Hebrew character code table
# CODEPAGE_ISO_8859_9 = 43  # Turkish character code table
# CODEPAGE_ISO_8859_15 = 44 # Latin 3 character code table
# CODEPAGE_THAI2 = 45       # Thai 2 character code page
# CODEPAGE_CP856 = 46       # Hebrew character code page
# CODEPAGE_CP874 = 47       # Thai character code page
